In [ ]:
import numpy as np
# 2468 /4096

In [ ]:
file_path  = 'domain_adapt/pseudo/1004_0519_soft/vis/2005_2434.npy'
data = np.load(file_path)

print("Shape of data:", data.shape)
print("Data type:", data.dtype)
print("First few values:\n", data[:5])


Shape of data: (1, 256, 256)
Data type: float32
First few values:
 [[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [ ]:

file_path  = '/data/wuhanUV_0519/imgs/train/1004_soft_instance/2005_1173_mask_1.npy'
data = np.load(file_path)

print("Shape of data:", data.shape)
print("Data type:", data.dtype)
print("First few values:\n", data[:5])
print(np.max(data))
print((data>0.5).sum())

Shape of data: (256, 256)
Data type: float32
First few values:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0.80094016
53
